### PR TITLE
Disable `clean-stack` and `ensure-error`

### PR DESCRIPTION
**Pull request by gasi**

### CODE REVIEW

**Comment by sindresorhus** [comment]
?

**Comment by gasi** [comment]
@sindresorhus Apologies, this is a change we need ourselves and was not meant to be a PR against the main project but rather against my own `master` branch. Will fix it 😄

**Comment by sindresorhus** [comment]
I would be happy to add an option to not use `ensure-error`. I can see the use-case for privacy-sensitive apps. I'm curious why you can't use `clean-stack` though. I didn't see anything about that in the Signal commits.

**Comment by gasi** [comment]
> I would be happy to add an option to not use ensure-error. I can see the use-case for privacy-sensitive apps.

Thanks, that would be helpful.

> I'm curious why you can't use clean-stack though.

We could but since we chose not to present these errors to users for now and our debug logs are submitted manually, it doesn’t hurt us to include the Node.js specific parts in the stack traces.

**Pull request closed without merging**
